### ISSUE TITLE
Plotting options

### ISSUE THREAD

**Issue by daramirez** [Dowell-Lab/TFEA#3]
Hi Jon,

I want to know if you can change the plot options such that the statistically significant changing TFs are labelled in the plots. And, for some datasets where I do see statistically significant changing TFs I still do not see their individual logo/motif figures. Is this the default expected behavior of TFEA? If this is the expected outcome, could you change it to display those individual significant TFs pIots? 

I currently only see the following output files and directories (the e_and_o directory being empty).

├── e_and_o
├── inputs.txt
├── mdd_results.txt
├── md_results.txt
├── plots
│   ├── DESEQ_MA_Plot.png
│   ├── MDD_MA.png
│   ├── MDD_volcano.png
│   ├── MD_MA.png
│   ├── MD_volcano.png
│   ├── TFEA_GC.png
│   └── TFEA_MA.png
├── rerun.sh
└── results.txt

Thanks!

**Comment by jdrubin91** [comment]
Hey Daniel,

You need to specify the —output_type ‘html’ to get individual TF plots. As far as labelling TFs on the MA-plot, we dont do that automatically but you can use the results.txt file to generate that type of plot with any labels you want.

Jonathan

**Comment by daramirez** [comment]
Understood. Thanks.
