### ISSUE TITLE
Error after E-scores are calculated, but results still produced

### ISSUE THREAD

**Issue by daramirez** [Dowell-Lab/TFEA#5]
Hello again,

I keep leaving these issues here solely based on my learning from Margaret that that is what she prefers from her repositories. Please let me know if I should stop doing this.

I encountered a different issue when using another PRO-seq dataset. I stopped using the flag '--plotall' and only used '--output_type html'. Though it seems that TFEA did its thing for the most part, as shown in the below output files, I also see that it still sort of crashed after TFEA finished calculating the E-scores, based on the error file that I am attaching here, and based on the fact that the temp_files folder was not removed. Is this a bug that affects the interpreation of the results that were produced?

.
├── e_and_o
├── inputs.txt
├── mdd_results.txt
├── md_results.txt
├── plots
│   ├── DESEQ_MA_Plot.png
│   ├── IRF1_M06920_1_enrichment_plot.png
│   ├── IRF1_M06920_1_simulation_plot.png
│   ├── IRF1_M08823_1_enrichment_plot.png
│   ├── IRF1_M08823_1_simulation_plot.png
│   ├── IRF3_M08827_1_enrichment_plot.png
│   ├── IRF3_M08827_1_simulation_plot.png
│   ├── IRF4_M08843_1_enrichment_plot.png
│   ├── IRF4_M08843_1_simulation_plot.png
│   ├── IRF9_M05855_1_enrichment_plot.png
│   ├── IRF9_M05855_1_simulation_plot.png
│   ├── IRF9_M08845_1_enrichment_plot.png
│   ├── IRF9_M08845_1_simulation_plot.png
│   ├── logoIRF1_M06920_1.eps
│   ├── logoIRF1_M06920_1.png
│   ├── logoIRF1_M08823_1.eps
│   ├── logoIRF1_M08823_1.png
│   ├── logoIRF3_M08827_1.eps
│   ├── logoIRF3_M08827_1.png
│   ├── logoIRF4_M08843_1.eps
│   ├── logoIRF4_M08843_1.png
│   ├── logoIRF9_M05855_1.eps
│   ├── logoIRF9_M05855_1.png
│   ├── logoIRF9_M08845_1.eps
│   ├── logoIRF9_M08845_1.png
│   ├── logoNRF1_M05963_1.eps
│   ├── logoNRF1_M05963_1.png
│   ├── logo_rcIRF1_M06920_1.eps
│   ├── logo_rcIRF1_M06920_1.png
│   ├── logo_rcIRF1_M08823_1.eps
│   ├── logo_rcIRF1_M08823_1.png
│   ├── logo_rcIRF3_M08827_1.eps
│   ├── logo_rcIRF3_M08827_1.png
│   ├── logo_rcIRF4_M08843_1.eps
│   ├── logo_rcIRF4_M08843_1.png
│   ├── logo_rcIRF9_M05855_1.eps
│   ├── logo_rcIRF9_M05855_1.png
│   ├── logo_rcIRF9_M08845_1.eps
│   ├── logo_rcIRF9_M08845_1.png
│   ├── logo_rcNRF1_M05963_1.eps
│   ├── logo_rcNRF1_M05963_1.png
│   ├── logo_rcSTAT2_M05474_1.eps
│   ├── logo_rcSTAT2_M05474_1.png
│   ├── logo_rcSTAT2_M06795_1.eps
│   ├── logo_rcSTAT2_M06795_1.png
│   ├── logo_rcZFP2_M07132_1.eps
│   ├── logo_rcZFP2_M07132_1.png
│   ├── logo_rcZNF76_M10350_1.eps
│   ├── logo_rcZNF76_M10350_1.png
│   ├── logoSTAT2_M05474_1.eps
│   ├── logoSTAT2_M05474_1.png
│   ├── logoSTAT2_M06795_1.eps
│   ├── logoSTAT2_M06795_1.png
│   ├── logoZFP2_M07132_1.eps
│   ├── logoZFP2_M07132_1.png
│   ├── logoZNF76_M10350_1.eps
│   ├── logoZNF76_M10350_1.png
│   ├── MDD_MA.png
│   ├── MDD_volcano.png
│   ├── MD_MA.png
│   ├── MD_volcano.png
│   ├── NRF1_M05963_1_enrichment_plot.png
│   ├── NRF1_M05963_1_simulation_plot.png
│   ├── STAT2_M05474_1_enrichment_plot.png
│   ├── STAT2_M05474_1.results.html
│   ├── STAT2_M05474_1_simulation_plot.png
│   ├── STAT2_M06795_1_enrichment_plot.png
│   ├── STAT2_M06795_1_simulation_plot.png
│   ├── TFEA_GC.png
│   ├── TFEA_MA.png
│   ├── ZFP2_M07132_1_enrichment_plot.png
│   ├── ZFP2_M07132_1_simulation_plot.png
│   ├── ZNF76_M10350_1_enrichment_plot.png
│   ├── ZNF76_M10350_1.results.html
│   └── ZNF76_M10350_1_simulation_plot.png
├── rerun.sh
├── results.txt
└── temp_files
    ├── combined_file.mumerge_BEDTOOLS_MERGE.bed
    ├── combined_file.mumerge.clean.bed
    ├── combined_file.mumerge.log
    ├── combined_file.mumerge_MISCALLS.bed
    ├── combined_file.mumerge_MUMERGE.bed
    ├── count_file.bed
    ├── count_file.header.bed
    ├── DESeq.R
    ├── DESeq.res.txt
    ├── DESeq.Rout
    ├── markov_background.txt
    ├── md1_fasta.fa
    ├── md2_fasta.fa
    ├── md_bedfile1.mumerge_BEDTOOLS_MERGE.bed
    ├── md_bedfile1.mumerge.final.bed
    ├── md_bedfile1.mumerge.log
    ├── md_bedfile1.mumerge_MISCALLS.bed
    ├── md_bedfile1.mumerge_MUMERGE.bed
    ├── md_bedfile2.mumerge_BEDTOOLS_MERGE.bed
    ├── md_bedfile2.mumerge.final.bed
    ├── md_bedfile2.mumerge.log
    ├── md_bedfile2.mumerge_MISCALLS.bed
    ├── md_bedfile2.mumerge_MUMERGE.bed
    ├── mdd1_fasta.fa
    ├── mdd2_fasta.fa
    ├── mdd_bedfile1.bed
    ├── mdd_bedfile2.bed
    ├── md_mumerge_input1.txt
    ├── md_mumerge_input2.txt
    ├── mumerge_input.txt
    ├── ranked_file.bed
    └── ranked_file.fa

Daniel

[20191223_tfea_error_log.txt](https://github.com/Dowell-Lab/TFEA/files/3995778/20191223_tfea_error_log.txt)

**Comment by daramirez** [comment]
Ah, I just looked more closely, and I see now that the resulting plots were not really finished. Such as the ZNF76_M10350_1.results.html being mostly blank.

**Comment by jdrubin91** [comment]
Hi Daniel,

Thank you for reporting this! I think I found the bug causing this issue. In the case of the single TF html file, I was log transforming values that did not need to be log transformed. This was resulting in the production of very large numbers that caused that overflow issue. I fixed this bug and pushed this change so when you get a chance could you try running it again to make sure this issue got fixed?

Thank you.

Jonathan
