### ISSUE TITLE
batch flag not passing batch names to DESeq.R script

### ISSUE THREAD

**Issue by joefranchesco** [Dowell-Lab/TFEA#8]
Hi Jon, sorry to bother you again. I just have one follow up question about that --batch flag. No rush at all, so ignore this if you're in the middle of things. I've been attempting to run TFEA using this flag. I'm using the --rank 'deseq' flag and the --batch 1,2,1,2 setup. I can see these both printed in my inputs.txt file, but when I peer into the DESeq.R script, it's receiving an empty list for batches that looks like this: batch <- c(). I was wondering if there's a different notation that I should use to feed the batches into the TFEA script to help them make it to the R script?

**Comment by jdrubin91** [comment]
Thanks for finding this Joe! This issue is fixed in the new v1.1.4
